version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Library@123
      - DB_NAME=library_management
      - JWT_SECRET=library_secret_key_123
      - CORS_ORIGIN=http://localhost:3001
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Library@123
      - MYSQL_DATABASE=library_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/config/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/src/config/auth_schema.sql:/docker-entrypoint-initdb.d/02-auth-schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:

networks:
  default:
    driver: bridge
