version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Library@123
      - DB_NAME=library_management
      - JWT_SECRET=library_secret_key_123
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Library@123
      - MYSQL_DATABASE=library_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/config/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/config/auth_schema.sql:/docker-entrypoint-initdb.d/2-auth-schema.sql

volumes:
  mysql_data:
